spring:
  application:
    name: "eurekaserver"
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:http://localhost:8071/}

# Actuator properties
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true